### ISSUE TITLE
price.php: Subscribe Code

### ISSUE THREAD

**Issue by rcass** [redacademy/linc-winter-2018#29]
This code below, I don't really understand what you are trying to achieve here. To me, this just need to be deleted, so I am curious to why this is here.
https://github.com/redacademy/linc-winter-2018/blob/ddb93fbd43ab2e2a27faab32d022d171357a0a4f/themes/linc-edge/price.php#L52-L86

**Comment by ghost** [comment]
**Response:**
Incorporated as a template to begin formatting corresponding PHP file foundation, has since been deleted from the project file: 

**Note:** PHP structure has been reformatted closed in issue #30 [**Reference ID to commit:** 

> https://github.com/redacademy/linc-winter-2018/commit/6a87bf15c34c50b9a3cc688c1c8aa954687d145c ]:

**Deleted segment:**
```
 <div class="subscription-form-container"> 
   <div class="subscription-form-content-container"> 
     <div class="subscription-form-group"> 
       <input class="email-field" type="email" name="EMAIL" placeholder="Email address" required /> 
       <input class="submit-button" type="submit" value="Subscribe" /> 
     </div><!-- .subscription-form-group --> 
   </div><!-- .subscription-form-content-container --> 
 </div><!-- .subscription-form-container --> 
```
Functional MailChimp for WP has been integrated.

**About segment:** 
```
 <div class="subscription-description-container"> 
   <?php $subscribes = CFS()->get( 'subscribe_description_content' ); foreach ( $subscribes as $subscribe ): ?> 
  
     <div class="subscription-description-content-container"> 
        
       <div class="subscription-description-group"> 
         <p class="subscription-description"><?php echo $subscribe['subscribe_description']; ?></p><!-- .subscription-description --> 
       </div><!-- .subscription-description-group --> 
  
     </div><!-- .subscription-description-content-container --> 
  
   <?php endforeach; ?><!-- ending foreach loop --> 
 </div><!-- .subscription-description-container --> 
```

Used to reference and 'get' content from the WP DB, the description (indicating purpose) of the e-mail subscription form.

**About segment:**
```
<div class="subscription-condition-container"> 
  
   <div class="subscription-condition-content-container"> 
     <?php $conditions = CFS()->get( 'subscribe_condition_content' ); foreach ( $conditions as $condition ): ?> 
  
       <div class="subscription-condition-group"> 
         <p class="subscription-condition"><?php echo $condition['subscribe_condition']; ?></p><!-- .subscription-condition --> 
       </div><!-- .subscription-condition-group --> 
  
     </div><!-- subscription-condition-content-container --> 
  
   <?php endforeach; ?><!-- ending foreach loop --> 
 </div><!-- .subscription-condition-container -->
```
Used to reference and 'get' content from the WP DB, the condition (indicating agreement) of the e-mail subscription form.

**Reference ID to commit:**

> https://github.com/redacademy/linc-winter-2018/commit/b95a7cb7d067419cc3ba782b537d7b64594e7c46
