### ISSUE TITLE
price.php: Code to remove

### ISSUE THREAD

**Issue by rcass** [redacademy/linc-winter-2018#30]
Here is some other code that just needs to be removed, if you think it should stay, just let me know why 👍 

- [x] Doesn't look like you are using this. https://github.com/redacademy/linc-winter-2018/blob/ddb93fbd43ab2e2a27faab32d022d171357a0a4f/themes/linc-edge/price.php#L19-L23

- [x] Are you actually using `the_content()`? https://github.com/redacademy/linc-winter-2018/blob/ddb93fbd43ab2e2a27faab32d022d171357a0a4f/themes/linc-edge/price.php#L18

- [x] Too many divs! Watch the output, you will find there is really no need to add these extra divs. Remove the excess divs please. https://github.com/redacademy/linc-winter-2018/blob/ddb93fbd43ab2e2a27faab32d022d171357a0a4f/themes/linc-edge/price.php#L31-L47

**Comment by ghost** [comment]
**Response:**
Incorporated as a template to begin formatting corresponding PHP file foundation, has since been deleted from the project file:

**Deleted segment #1:**
```
<?php wp_link_pages( array( 
   'before' => '<div class="page-links">' . esc_html( 'Pages:' ), 
   'after'  => '</div>', ) ); 
?> 
``` 

**Deleted segment #2:**
```
 <?php the_content(); ?> 
```

**Updated segment #3:**
The unneeded and unused DIV(s) has been deleted from the project file and the corresponding SCSS file. The SCSS file has also been refactored.

**Reference ID to commit:**

> https://github.com/redacademy/linc-winter-2018/commit/6a87bf15c34c50b9a3cc688c1c8aa954687d145c
